# Start second (arm64v8) stage
FROM node:lts-alpine AS builder

# Define some ENV Vars
ENV PORT=80 \
    DIRECTORY=/app \
    IS_DOCKER=true

# Create and set the working directory
WORKDIR ${DIRECTORY}

# Copy over both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# Install project dependencies
RUN yarn

# Copy over all project files and folders to the working directory
COPY . .

# Build initial app for production
RUN yarn build

# Multi arch build support
FROM alpine as qemu

ARG QEMU_VERSION="v4.2.0-7"

RUN wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_VERSION}/qemu-aarch64-static && chmod +x qemu-aarch64-static

# production stage
FROM arm64v8/alpine:3.11

COPY --from=qemu qemu-aarch64-static /usr/bin/

# Expose given port
EXPOSE ${PORT}

# Finally, run start command to serve up the built application
CMD [ "yarn", "build-and-start"]

# Run simple healthchecks every 5 mins, to check the Dashy's everythings great
HEALTHCHECK --interval=5m --timeout=2s --start-period=30s CMD yarn health-check
