/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  dashySidebar: [
    {
      type: 'category',
      label: 'Running Dashy',
      items: ['quick-start', 'deployment', 'configuring', 'management', 'troubleshooting'],
    },
    {
      type: 'category',
      label: 'Feature Docs',
      items: [
        'icons', 'widgets', 'theming', 'status-indicators',
        'authentication', 'searching', 'alternate-views',
        'multi-language-support', 'backup-restore', 'pages-and-sections',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: ['showcase', 'contributing', 'developing', 'development-guides'],
    },
    {
      type: 'category',
      label: 'Misc',
      items: ['privacy', 'changelog', 'license', 'code-of-conduct'],
    },
  ],

};

