name: Feature Request ✨
description: Suggest an idea for future development of Dashy
title: '[FEATURE_REQUEST] <title>'
labels: ['🦄 Feature Request']

body:

  # Field 1 - Is it bug-related
  - type: textarea
    id: issue
    attributes:
      label: Is your feature request related to a problem? If so, please describe.
      description:
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false

  # Field 2 - Describe feature
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: An outline of how you would like this to be implemented, include as much details as possible 
    validations:
      required: true

  # Field 3 - Priority
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is the development of this feature
      options:
        - Low (Nice-to-have)
        - Medium (Would be very useful)
        - High (The app does not function without it)
    validations:
      required: true

  # Field 3 - Can the user implement
  - type: dropdown
    id: canImplement
    attributes:
      label: Is this something you would be keen to implement
      description: Are you raising this ticket in order to get an issue number for your PR?
      options:
        - 'No'
        - 'Maybe'
        - 'Yes!'
    validations:
      required: false

  # Final text
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Thank you for your feature suggestion, you should expect a reply within 48 hours :)
        Please note that there is no guarantee that your idea will be implemented
        If you haven't already done so, please Star the Dashy's repository on GitHub, to help other users discover it
    validations:
      required: false