module.exports = {
  iconSize: 'medium',
  layout: 'auto',
  defaultTheme: 'default',
  builtInThemes: [
    'nord',
    'nord-frost',
    'callisto',
    'thebe',
    'material',
    'dracula',
    'matrix',
    'matrix-red',
    'hacker-girl',
    'bee',
    'raspberry-jam',
    'tiger',
    'colorful',
    'high-contrast-light',
    'high-contrast-dark',
  ],
  visibleComponents: {
    pageTitle: true,
    navigation: true,
    searchBar: true,
    settings: true,
    footer: true,
  },
};
