---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dashy.fullname" . }}
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
data:
  {{- if and .Values.dashy .Values.dashy.config }}
  {{- if kindIs "string" .Values.dashy.config }}
  conf.yml: {{ .Values.dashy.config | b64enc | nindent 4 }}
  {{- else if kindIs "map" .Values.dashy.config }}
  conf.yml: {{ .Values.dashy.config | toYaml | b64enc | nindent 4 }}
  {{- else }}
  conf.yml: ""
  {{- end }}
  {{- end }}
