# Builds the dashy docs website (docusrus), and puts the compiled output into the gh-pages branch
# From there, it can be served/deployed to GitHub Pages, or any other static CDN or hosting provider
name: 💼 Build Docs Site
on:
  workflow_dispatch:
  push:
    branches: [WEBSITE/docs-site-source]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/WEBSITE/docs-site-source'
    steps:
      - name: Check check checkin it out
        uses: actions/checkout@v4

      - name: Setup Node 22 with yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Enable Corepack so we can yarn
        run: corepack enable

      - name: Install a shit ton of crap
        run: yarn install --frozen-lockfile

      - name: Build everything
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to the world
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          cname: dashy.to
