name: 🐳 Build + Publish Multi-Platform Image

on:
  workflow_dispatch:
  push:
    tags: ['*.*.*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

env:
  DH_IMAGE: ${{ secrets.DOCKER_REPO }}
  GH_IMAGE: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }

    steps:
    - name: 🛎️ Checkout Repo
      uses: actions/checkout@v6

    - name: 🗂️ Make Docker Meta
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: |
          ${{ env.DH_IMAGE }}
          ghcr.io/${{ env.GH_IMAGE }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}.x
          type=raw,value=latest
        flavor: |
          latest=false

    - name: ⏱️ Capture Build Timestamp
      id: timestamp
      run: echo "iso=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

    - name: 🔧 Set up QEMU
      uses: docker/setup-qemu-action@v4
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: 🔧 Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: 🔑 Login to DockerHub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🔑 Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🚦 Check Registry Status
      uses: crazy-max/ghaction-docker-status@v4

    - name: ⚒️ Build and Push
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          VERSION=${{ steps.meta.outputs.version }}
          REVISION=${{ github.sha }}
          CREATED=${{ steps.timestamp.outputs.iso }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
