# Syncs the full source of the Dashy repo over to our Codeberg mirror
# For all you non-Microsoft babes!
# This is then accessible over at https://codeberg.org/alicia/dashy
name: 🪞 Mirror to Codeberg
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 0' # At 03:30 on Sunday
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: lissy93/repo-mirror-action@v1.5.0
        with:
          ssh_key: ${{ secrets.CODEBERG_SSH }}
          host: git@codeberg.org
          user: alicia
          repo: dashy
          force_push: false
